# Header

menu:
  主页: /
  # 随笔: /tags/随笔/

# SubNav
subnav:
  github: "https://github.com/heroims"
  # weibo: "#"
  rss: /atom.xml
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  jianshu: "http://www.jianshu.com/u/8ece68b113e5"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:heroims@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  linkedin: "https://www.linkedin.com/in/%E6%98%93%E5%A5%87-%E8%B5%B5-8aa943aa/?ppe=1"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: 'more'
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '查看全文'

# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

fancybox: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: 'https://avatars3.githubusercontent.com/u/1631701?v=4&s=460'

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#ffffff,#000000)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  简书: http://www.jianshu.com/u/8ece68b113e5
  无聊练手网页:  http://heroims.github.io/MyWeblog/

aboutme: 现阶段很想进个bat<br><br>有能推荐的希望推荐下<br>谢谢大家